typography_spectrum: 0.34956700750626624
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5972167940344661
  lightness: 0.98422308312729
  saturation: 0.8626534298527986
  rhythmicContrast: 0.302095505874604
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07739744428545237
analytics:
  google: null
  facebook: null
  twitter: null
name: Product Packaging
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: one grocery store at a time
purpose: []
